import logging

import httpx

from app.config import Settings
from app.providers.base import AiProvider

logger = logging.getLogger("ai-service.gemini")


class GeminiProvider(AiProvider):
    name = "gemini"

    def __init__(self, settings: Settings):
        self._api_key = settings.gemini_api_key
        self._model = settings.gemini_model
        self._timeout = settings.request_timeout_seconds
        self._url = (
            f"https://generativelanguage.googleapis.com/v1beta/models/{self._model}:generateContent"
        )

    async def generate_response(self, prompt: str) -> str:
        if not self._api_key:
            return "The AI assistant is not configured yet. Please set GEMINI_API_KEY on the server."

        payload = {"contents": [{"parts": [{"text": prompt}]}]}

        try:
            async with httpx.AsyncClient(timeout=self._timeout) as client:
                response = await client.post(
                    self._url,
                    params={"key": self._api_key},
                    json=payload,
                    headers={"Content-Type": "application/json"},
                )
                response.raise_for_status()
                data = response.json()

            if "error" in data:
                message = data["error"].get("message", "Unknown Gemini error")
                logger.error("Gemini API error: %s", message)
                return f"Gemini API Error: {message}"

            candidates = data.get("candidates") or []
            if candidates:
                parts = candidates[0].get("content", {}).get("parts", [])
                if parts:
                    return parts[0].get("text", "No response generated by Gemini")

            return "No response generated by Gemini"

        except httpx.HTTPStatusError as exc:
            logger.error("Gemini HTTP error: %s - %s", exc.response.status_code, exc.response.text)
            return "Sorry, the AI assistant is temporarily unavailable. Please try again shortly."
        except Exception:
            logger.exception("Gemini API call failed")
            return "Sorry, the AI assistant is temporarily unavailable. Please try again shortly."
