<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>SmartLearningHub.CertificateService.Api</RootNamespace>
    <UserSecretsId>smart-learning-hub-certificate-service</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartLearningHub.CertificateService.Application\SmartLearningHub.CertificateService.Application.csproj" />
    <ProjectReference Include="..\SmartLearningHub.CertificateService.Infrastructure\SmartLearningHub.CertificateService.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="GeneratedCertificates\**" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
